Description Switch toegevoegd
nl-design-system/documentatie pull request #1107
Opened 2024-07-04 13:24 UTC by Rozerinay

2024-07-07 20:21 UTC, Robbert requested changes

2024-07-07 20:21 UTC, Robbert commented on docs/componenten/switch/index.mdx
> +export const description = "Biedt de mogelijkheid om tussen twee statussen te schakelen, zoals aan of uit.";
Bij een switch is zijn er niet andere mogelijkheden dan aan of uit, dat is de enige optie.

Invoerveld om een optie "aan" of "uit" te zetten.

2024-07-08 14:13 UTC, Rozerinay commented on docs/componenten/switch/index.mdx
> +export const description = "Biedt de mogelijkheid om tussen twee statussen te schakelen, zoals aan of uit.";
Goed voorstel. Is er een reden waarom je de woorden 'aan' en 'uit' tussen aanhalingstekens hebt geplaatst?

2024-07-09 06:36 UTC, Robbert commented on docs/componenten/switch/index.mdx
> +description: Biedt de mogelijkheid om tussen twee statussen te schakelen, zoals aan of uit.
```suggestion
description: Invoerveld om een optie aan of uit te zetten.
```

2024-07-09 06:36 UTC, Robbert commented on docs/componenten/switch/index.mdx
> +export const description = "Biedt de mogelijkheid om tussen twee statussen te schakelen, zoals aan of uit.";
```suggestion
export const description = "Invoerveld om een optie aan of uit te zetten.";
```

2024-07-09 06:36 UTC, Robbert commented on docs/componenten/switch/index.mdx
> +export const description = "Biedt de mogelijkheid om tussen twee statussen te schakelen, zoals aan of uit.";
Beter om geen aanhalingstekens te gebruiken inderdaad.

2024-07-09 06:37 UTC, Robbert approved these changes

2024-07-09 06:42 UTC, merged