Description Toggletip toegevoegd
nl-design-system/documentatie pull request #1113
Opened 2024-07-04 14:09 UTC by Rozerinay

2024-07-08 21:37 UTC, Robbert requested changes

2024-07-08 21:37 UTC, Robbert commented on docs/componenten/toggletip/index.mdx
> +description: Biedt de mogelijkheid om aanvullende informatie te tonen die is verborgen.
De huidige omschrijving noemt niet de unieke eigenschappen van de Toggletip. Deze beschrijving zou ook werken voor bijvoorbeeld Details of Accordion.

Mijn voorstel:
Een knop om tijdelijk informatie te tonen, die automatisch weer verborgen wordt wanneer je iets anders dan de knop gebruikt.

2024-07-09 07:26 UTC, Rozerinay commented on docs/componenten/toggletip/index.mdx
> +description: Biedt de mogelijkheid om aanvullende informatie te tonen die is verborgen.
Goed punt. Misschien kunnen we de zin nog wat vloeiender maken en het woord 'je' vermijden. 

Mijn voorstel:
Een knop die tijdelijke informatie toont en deze automatisch verbergt wanneer iets anders dan de knop wordt gebruikt. 

Of misschien wat specifieker:
Een knop die tijdelijke informatie toont en deze automatisch verbergt wanneer ergens anders op de pagina wordt geklikt.

2024-07-09 09:51 UTC, Robbert commented on docs/componenten/toggletip/index.mdx
> +description: Biedt de mogelijkheid om aanvullende informatie te tonen die is verborgen.
```suggestion
description: Een knop die tijdelijke informatie toont en deze automatisch verbergt wanneer iets anders dan de knop wordt gebruikt.
```

2024-07-09 09:51 UTC, Robbert commented on docs/componenten/toggletip/index.mdx
> +export const description = "Biedt de mogelijkheid om aanvullende informatie te tonen die is verborgen.";
```suggestion
export const description = "Een knop die tijdelijke informatie toont en deze automatisch verbergt wanneer iets anders dan de knop wordt gebruikt.";
```

2024-07-09 09:51 UTC, Robbert approved these changes

2024-07-22 15:09 UTC, Robbert commented
Fixed in #1159

2024-07-22 15:09 UTC, closed without merging