Description Checkbox toegevoegd.mdx
nl-design-system/documentatie pull request #1126
Opened 2024-07-04 15:01 UTC by jeffreylauwers

2024-07-07 18:04 UTC, Robbert requested changes

2024-07-07 18:04 UTC, Robbert commented on docs/componenten/checkbox/index.mdx
> +description: Toont een visuele indicatie van een optie binnen een Form field checkbox option en biedt de mogelijkheid om die optie te selecteren.
Deze beschrijving voelt voor mij wel heel complex geworden...

Mijn voorstel:
Invoerveld voor een optie kiezen uit een groep van opties, of om te kiezen tussen "wel" of "niet".

2024-07-08 13:31 UTC, jeffreylauwers commented on docs/componenten/checkbox/index.mdx
> +description: Toont een visuele indicatie van een optie binnen een Form field checkbox option en biedt de mogelijkheid om die optie te selecteren.
Hij is ook complex. Maar ik vind het voorstel nog steeds complex. Deze moeten we in combinatie met Checkbox group, Form field checkbox option, Radio, Radio group en Form field radio option. Nogmaals bespreken.

[Bij Radio schrijf je het volgende](https://github.com/nl-design-system/documentatie/pull/1101#discussion_r1667740550):
_Invoerveld voor het kiezen van een enkele optie uit een groep met meerdere opties._

Dus dan misschien?
_Invoerveld voor het kiezen van één of meerdere opties uit een groep met meerdere opties._

Maar hoe verschilt dit doel dan van Form field checkbox option en Form field radio option...

2024-07-09 09:16 UTC, Robbert commented on docs/componenten/checkbox/index.mdx
> +description: Toont een visuele indicatie van een optie binnen een Form field checkbox option en biedt de mogelijkheid om die optie te selecteren.
Rozerin zegt: Invoerveld voor het kiezen van een optie uit een groep van opties, of om te kiezen tussen "wel" of "niet".

2024-07-09 09:17 UTC, Robbert commented on docs/componenten/checkbox/index.mdx
> +description: Toont een visuele indicatie van een optie binnen een Form field checkbox option en biedt de mogelijkheid om die optie te selecteren.
```suggestion
description: Invoerveld voor het kiezen van een optie uit een groep van opties, of om te kiezen tussen "wel" of "niet".
```

2024-07-09 09:17 UTC, Robbert commented on docs/componenten/checkbox/index.mdx
> +export const description = "Toont een visuele indicatie van een optie binnen een Form field checkbox option en biedt de mogelijkheid om die optie te selecteren.";
```suggestion
export const description = 'Invoerveld voor het kiezen van een optie uit een groep van opties, of om te kiezen tussen "wel" of "niet".';
```

2024-07-22 15:07 UTC, Robbert commented
Fixed in #1159

2024-07-22 15:07 UTC, closed without merging