Voeg richtlijnen over status toe
nl-design-system/documentatie pull request #1317
Opened 2024-08-15 14:50 UTC by hidde

2024-08-19 08:38 UTC, rianrietveld requested changes
@hidde 
Duidelijk verhaal tot nu toe 🙌 
Ik heb wat opmerkingen geplaatst.

2024-08-19 08:38 UTC, rianrietveld commented on docs/richtlijnen/formulieren/status/1-screenreaders/_guideline.md
> +Een element met role="alert" is een “assertive” live region, en functioneel gelijk aan het gebruiken van de combinatie [aria-live="assertive"](https://developer.mozilla.org/en-US/docs/Web/Accessibili
We heben afgesproken enkele haakjes te gebruiken als aanhalingstekens.
“assertive” -> 'assertive'

2024-08-19 08:38 UTC, rianrietveld commented on docs/richtlijnen/formulieren/status/1-screenreaders/_guideline.md
> +- [https://tetralogical.com/blog/2024/05/01/why-are-my-live-regions-not-working/](https://tetralogical.com/blog/2024/05/01/why-are-my-live-regions-not-working/)
link tekst en ook auteur vermelden.

2024-08-19 08:38 UTC, rianrietveld commented on docs/richtlijnen/formulieren/status/2-zoomed-in/_guideline.md
> +Zet bijvoorbeeld dynamisch gegenereerde meldingen voor een formulier altijd vlak bij het formulierveld bovenaan de pagina. Zoals de melding over het totaal aantal ingevoerde karakters voor een tekstv
> vlak bij het formulierveld  bovenaan de pagina
Ik denk dat hier iets is weggevallen in mijn oorgspronkelijke tekst, want dit is niet logisch.

Voorstel:
vlak bij het formulierveld of bijvoorbeeld bovenaan de pagina, afhankelijk van waar en wanneer de foutmelding getoond wordt.

2024-08-19 08:38 UTC, rianrietveld commented on docs/richtlijnen/formulieren/status/3-enough-time/_guideline.md
> +Soms is een statusmelding afhankelijk van tijd, bijvoorbeeld “bezig met uploaden…”, “aan het verzenden…”. Dan kan het betekenisvol zijn om de melding vanzelf te laten verdwijnen om te communiceren da
Goed omschreven!

2024-08-21 16:16 UTC, hidde commented on docs/richtlijnen/formulieren/status/1-screenreaders/_guideline.md
> +- [https://tetralogical.com/blog/2024/05/01/why-are-my-live-regions-not-working/](https://tetralogical.com/blog/2024/05/01/why-are-my-live-regions-not-working/)
Ah ja, toegevoegd in zelfde formaat als elders

2024-08-21 16:18 UTC, hidde commented
@rianrietveld Super, dank voor de feedback, ik heb het verwerkt, dus hij is weer klaar voor jouw review.

2024-08-26 05:00 UTC, rianrietveld approved these changes
@hidde LGTM

2024-08-26 05:01 UTC, merged