Voeg communitybijeenkomst signup toe
nl-design-system/documentatie pull request #1379
Opened 2024-09-11 11:56 UTC by hidde

@Robbert kun jij vooral de code checken?

@RenateNLDS kun jij vooral de tekst op de [aanmeldpagina](https://github.com/nl-design-system/documentatie/pull/1379/files#diff-f197913a77de58ea5de096c457ba2476946b7b07be69d8c02e4d917a89ce4a0dR13) en de [bedankpagina](https://github.com/nl-design-system/documentatie/pull/1379/files#diff-14f77701f8d9838114282e3adf4d176dd9cc924abaad52247b1619b2b3ba45e9R15) checken?

## context

Dit maakt aanmelden voor communityborrel mogelijk met een formulier. 

Technisch komt men op een event-specifieke La Posta lijst, die straks het overzicht kan geven van wie er komt. 

Afmelden kan via de link in de automatische reactie op je aanmelding, je verwijdert jezelf dan weer uit dezelfde lijst. 

## nieuwe features

De `NewsletterSignup` component plaatst vult nu de naam en emailvelden al in als je respectievelijk `prefillName` en/of `prefillEmail` meegeeft als URL parameters. Zo kunnen we de community mailen en mensen met 1 klik laten aanmelden met dezelfde gegevens die ze al hadden gedeeld.

2024-09-11 12:15 UTC, RenateNLDS requested changes
Ik zou niet zeggen 2e communityborrel, maar gewoon de communityborrel of de datum erbij.

2024-09-12 06:54 UTC, RenateNLDS reviewed
Ik zie niks raars.

2024-09-12 09:39 UTC, RenateNLDS approved these changes

2024-09-12 12:02 UTC, Yolijn approved these changes

2024-09-12 12:09 UTC, merged