Voeg meer sprekers en sessies toe
nl-design-system/documentatie pull request #1380
Opened 2024-09-11 13:54 UTC by hidde

(Let op: ligt nog ter check bij sommige sprekers)

2024-09-12 09:53 UTC, RenateNLDS commented on docs/community/events/design-systems-week-2024/speakers.json
> +      "nl": "Bart Veneman is frontend architect bij Drukwerkdeal.nl. In zijn vrije tijd werkt hij aan Project Wallace, een project om informatie over de CSS in een website te verzamelen over een lang
Bart Veneman is frontend architect bij Drukwerkdeal.nl. In zijn vrije tijd werkt hij aan Project Wallace, een project om informatie over de CSS in een website te verzamelen over een langere periode. Dit project is gericht op developers die de complexiteit van hun CSS in de gaten willen houden en voor designers die willen weten of de juiste kleuren en lettertypes zijn gebruikt.

2024-09-12 09:56 UTC, RenateNLDS requested changes
Ik heb 2 suggestie gedaan i.v.m lange zin.

2024-09-12 09:56 UTC, RenateNLDS commented on docs/community/events/design-systems-week-2024/programma.md
> +<Paragraph>In deze sessie vertellen Vincent, Warre en Gijs over de evolutie van het Vlaams Design System: hoe het evolueerde van een bibliotheek met web componenten naar een dienstverlening om van bi
In deze sessie vertellen Vincent, Warre en Gijs over de evolutie van het Vlaams Design System. Hoe het evolueerde van een bibliotheek met webcomponenten naar een dienstverlening om van bij de start bouwers van e-loketten, toepassingen en websites te ondersteunen bij het ontwerpen en ontwikkelen. Met als focus: een herkenbare en eengemaakte gebruikerservaring voor burgers.

2024-09-12 09:56 UTC, RenateNLDS commented on docs/community/events/design-systems-week-2024/speakers.json
> +      "nl": "Bart Veneman is frontend architect bij Drukwerkdeal.nl. In zijn vrije tijd werkt hij aan Project Wallace, een project om informatie over de CSS in een website te verzamelen over een lang
Bart Veneman is frontend architect bij Drukwerkdeal.nl. In zijn vrije tijd werkt hij aan Project Wallace, een project om informatie over de CSS in een website te verzamelen over een langere periode. Dit project is gericht op developers die de complexiteit van hun CSS in de gaten willen houden en voor designers die willen weten of de juiste kleuren en lettertypes zijn gebruikt.

2024-09-12 12:10 UTC, hidde commented on docs/community/events/design-systems-week-2024/speakers.json
> +      "nl": "Bart Veneman is frontend architect bij Drukwerkdeal.nl. In zijn vrije tijd werkt hij aan Project Wallace, een project om informatie over de CSS in een website te verzamelen over een lang
verbeterd!

2024-09-12 12:10 UTC, hidde commented on docs/community/events/design-systems-week-2024/programma.md
> +<Paragraph>In deze sessie vertellen Vincent, Warre en Gijs over de evolutie van het Vlaams Design System: hoe het evolueerde van een bibliotheek met web componenten naar een dienstverlening om van bi
verbeterd, thanks!

2024-09-13 07:42 UTC, Yolijn approved these changes

2024-09-13 07:42 UTC, merged