docs: WCAG 2.2.6 Time-outs - summary
nl-design-system/documentatie pull request #1414
Opened 2024-09-23 09:17 UTC by rianrietveld

Gerelateerd issue: #1304

2024-10-04 13:43 UTC, MarjonBakker commented on docs/wcag/summaries/_2.2.6-summary.md
> +Waarschuw de gebruiker vooraf dat gegevens verloren kunnen gaan, als deze wordt uitgelogd vanwege hun inactiviteit op de website. Behalve wanneer deze gegevens meer dan 20 uur bewaard worden.
'hun' (meervoud) slaat hier op 'gegevens' (meervoud) en niet op 'de gebruiker' (enkelvoud). Dat maakt de zin krom.

2024-10-04 13:45 UTC, MarjonBakker commented on docs/wcag/summaries/_2.2.6-summary.md
> +**Let op:** Als dit privacygevoelige gegevens zijn, moet de gebruiker wel eerst toestemming geven voor het bewaren van deze data.
Het advies is ook om deskundigen in te schakelen als het om minderjarigen gaat, moet dat hier niet ook bij?

2024-10-04 13:45 UTC, MarjonBakker requested changes
Zie comments in de tekst.

2024-10-08 07:12 UTC, rianrietveld commented on docs/wcag/summaries/_2.2.6-summary.md
> +**Let op:** Als dit privacygevoelige gegevens zijn, moet de gebruiker wel eerst toestemming geven voor het bewaren van deze data.
Oh ja, ik heb ervan gemaakt:

> **Let op:** Als dit privacygevoelige gegevens zijn, moet de gebruiker wel eerst toestemming geven voor het bewaren van deze data. Dit is opgenomen in de Algemene verordening gegevensbescherming (AVG).
> 
> Kinderen jonger dan 16 jaar kunnen zelf geen geldige toestemming geven voor het verwerken van hun gegevens. Toestemming is alleen geldig als een van de ouders of verzorgers van een kind de toestemming geeft.
> 
> Overleg zonodig met privacyprofessionals en vraag juridisch advies om aan dit succescriterium te voldoen.

2024-10-08 08:40 UTC, MarjonBakker approved these changes

2024-10-10 06:56 UTC, merged