docs: WCAG-pagina 2.3.3 Animatie uit interacties - summary
nl-design-system/documentatie pull request #1420
Opened 2024-09-24 06:24 UTC by rianrietveld

Voegt pagina met samenvatting WCAG-pagina 2.3.3 Animatie uit interacties toe.
Gerelateerd issue #1304

2024-10-04 13:48 UTC, MarjonBakker commented on docs/wcag/2.3.03.mdx
> +- Engelstalige toelichting: [<span lang="en">Understanding SC 2.3.3 TAnimation from Interactions</span>](https://www.w3.org/WAI/WCAG22/Understanding/animation-from-interactions.html).
`Understanding SC 2.3.3 TAnimation` --> `Understanding SC 2.3.3 Animation`

2024-10-04 14:01 UTC, MarjonBakker commented on docs/wcag/summaries/_2.3.3-summary.md
> +Zorg ervoor dat een gebruiker toegevoegde extra beweging en animatie uit kan zetten op interactieve elementen, zoals een link, button of checkbox. Behalve als de animatie essentieel is voor de functi
Ik vind de term 'toegevoegde extra beweging en animatie' nog ietwat vaag. Het maakt niet duidelijk dat het gaat om beweging en animatie die de gebruiker zelf start door interactie met de website.

2024-10-04 14:01 UTC, MarjonBakker requested changes
Zie inline comments.

2024-10-08 07:21 UTC, rianrietveld commented on docs/wcag/summaries/_2.3.3-summary.md
> +Zorg ervoor dat een gebruiker toegevoegde extra beweging en animatie uit kan zetten op interactieve elementen, zoals een link, button of checkbox. Behalve als de animatie essentieel is voor de functi
Ik heb ervan gemaakt: 

> Zorg ervoor dat de gebruiker beweging en animatie uit kan zetten. Dit gaat over beweging die de gebruiker zelf start door interactie met interactieve elementen, zoals bij een link, button of checkbox.

2024-10-08 08:44 UTC, MarjonBakker approved these changes

2024-10-10 06:55 UTC, merged