docs: WCAG 2.4.8 Locatie - summary
nl-design-system/documentatie pull request #1421
Opened 2024-09-24 07:12 UTC by rianrietveld

Voegt pagina met samenvatting "WCAG-pagina 2.4.8 Locatie" toe.
Gerelateerd issue https://github.com/nl-design-system/documentatie/issues/1304
Preview: https://documentatie-git-docs-wcag-248-summary-nl-design-system.vercel.app/wcag/2.4.8

2024-10-04 14:07 UTC, MarjonBakker commented on docs/wcag/summaries/_2.4.8-summary.md
> +Dit is voor iedereen fijn, maar speciaal ook voor mensen met een cognitieve beperking. Ook bezoekers, die via een zoekmachine en niet via de homepagina binnenkomen, begrijpen dan waar ze zich bevinde
'Ook bezoekers, die via een zoekmachine en niet via de homepagina binnenkomen, begrijpen dan waar ze zich bevinden.'

De komma's mogen hier weg: De tekst ertussen is geen bijzin.

2024-10-04 14:11 UTC, MarjonBakker requested changes
Zie comment inline

2024-10-07 08:45 UTC, rianrietveld commented on docs/wcag/summaries/_2.4.8-summary.md
> +Dit is voor iedereen fijn, maar speciaal ook voor mensen met een cognitieve beperking. Ook bezoekers, die via een zoekmachine en niet via de homepagina binnenkomen, begrijpen dan waar ze zich bevinde
Is aangepast

2024-10-08 09:03 UTC, MarjonBakker approved these changes

2024-10-10 06:55 UTC, merged