docs: WCAG 2.5.6 Input gelijktijdige invoermechanismen - summary
nl-design-system/documentatie pull request #1430
Opened 2024-09-27 06:08 UTC by rianrietveld

Voegt pagina met samenvatting "2.5.6 Input gelijktijdige invoermechanismen" toe.
Gerelateerd issue https://github.com/nl-design-system/documentatie/issues/1304
Preview: https://documentatie-git-docs-wcag-256-summary-nl-design-system.vercel.app/wcag/2.5.6

2024-10-10 06:17 UTC, MarjonBakker commented on docs/wcag/2.5.06.mdx
> +- Nederlandse vertaling van het WCAG-succescriterium: [2.5.6 Input gelijktijdige invoermechanismen](https://www.w3.org/Translations/WCAG22-nl/#nput-gelijktijdige-invoermechanismen).
`https://www.w3.org/Translations/WCAG22-nl/#nput-gelijktijdige-invoermechanismen` veranderen in `https://www.w3.org/Translations/WCAG22-nl/#input-gelijktijdige-invoermechanismen`

2024-10-10 06:23 UTC, MarjonBakker commented on docs/wcag/summaries/_2.5.6-summary.md
> +Laat gebruikers inhoud invoeren op een wijze die voor hen het gemakkelijkste is, en dit kan afhankelijk zijn van het soort invoer. Dus switchen moet mogelijk zijn.
Voorstel: 'Laat gebruikers inhoud invoeren op een wijze die voor hen het gemakkelijkste is. Dit kan afhankelijk zijn van het soort invoer, dus switchen moet mogelijk zijn.' (punten en komma's anders geplaatst)

2024-10-10 06:24 UTC, MarjonBakker commented on docs/wcag/summaries/_2.5.6-summary.md
> +Het beperken van verschillende manieren van invoeren kan als deze:
`als deze:` vervangen door `als dit:`

2024-10-10 06:25 UTC, MarjonBakker requested changes
Linkfix, 2 stijlcomments

2024-10-10 08:58 UTC, MarjonBakker commented on docs/wcag/2.5.06.mdx
> +description: Geef een gebruiker de mogelijkheid om de website te gebruiken met alle beschikbare invoermanieren die op hun platform beschikbaar zijn. Behalve wanneer een bepaalde manier van invoeren e
Gelijktrekken met summary: 

`Geef een gebruiker de mogelijkheid om de website of app te gebruiken met alle beschikbare invoermanieren die op hun platform beschikbaar zijn. Behalve wanneer een bepaalde manier van invoeren essentieel of vereist is.`

2024-10-11 06:48 UTC, rianrietveld commented on docs/wcag/2.5.06.mdx
> +- Nederlandse vertaling van het WCAG-succescriterium: [2.5.6 Input gelijktijdige invoermechanismen](https://www.w3.org/Translations/WCAG22-nl/#nput-gelijktijdige-invoermechanismen).
is aangepast

2024-10-11 06:49 UTC, rianrietveld commented on docs/wcag/summaries/_2.5.6-summary.md
> +Het beperken van verschillende manieren van invoeren kan als deze:
is aangepast

2024-10-11 06:50 UTC, rianrietveld commented on docs/wcag/2.5.06.mdx
> +description: Geef een gebruiker de mogelijkheid om de website te gebruiken met alle beschikbare invoermanieren die op hun platform beschikbaar zijn. Behalve wanneer een bepaalde manier van invoeren e
is aangepast

2024-10-11 07:04 UTC, MarjonBakker approved these changes

2024-10-11 07:05 UTC, merged