docs: wcag 3.1.5 Leesniveau - summary
nl-design-system/documentatie pull request #1433
Opened 2024-09-27 08:48 UTC by rianrietveld

Voegt pagina met samenvatting "3.1.5 Leesniveau" toe.
Gerelateerd issue https://github.com/nl-design-system/documentatie/issues/1304
Preview: https://documentatie-git-docs-wcag-315-summary-nl-design-system.vercel.app/wcag/3.1.5

2024-10-10 08:45 UTC, MarjonBakker commented on docs/wcag/3.1.05.mdx
> +description: Zorg ervoor dat teksten begrijpelijk zijn voor een lezer uit tenminste de tweede klas van het middelbaar onderwijs. Of bied ook een eenvoudig leesbare versie van de tekst aan als alterna
Pas ook de description aan, zie https://github.com/nl-design-system/documentatie/pull/1433/files#r1794987643

2024-10-10 08:46 UTC, MarjonBakker requested changes
iets andere formulering

2024-10-11 06:43 UTC, rianrietveld commented on docs/wcag/summaries/_3.1.5-summary.md
> +Zorg ervoor dat de teksten begrijpelijk zijn voor een lezer uit tenminste de tweede klas van het middelbaar onderwijs. Of bied ook een eenvoudig leesbare versie van de tekst aan als alternatief.
is aangepast

2024-10-11 06:43 UTC, rianrietveld commented on docs/wcag/3.1.05.mdx
> +description: Zorg ervoor dat teksten begrijpelijk zijn voor een lezer uit tenminste de tweede klas van het middelbaar onderwijs. Of bied ook een eenvoudig leesbare versie van de tekst aan als alterna
is aangepast

2024-10-11 07:01 UTC, MarjonBakker approved these changes

2024-10-11 07:06 UTC, merged