Docs: succescriteria bij component mark
nl-design-system/documentatie pull request #1634
Opened 2024-11-12 14:35 UTC by MarjonBakker

Gerelateerd issue: https://github.com/nl-design-system/documentatie/issues/1375

2024-11-13 06:12 UTC, rianrietveld commented
@MarjonBakker beetje weird met de /, ik kon die niet comitten en ik zag um ook niet hierbij staan.
Als workaround heb ik de tekst

> In het geval van het Mark component is dat het HTML-element `mark`.

Aangepast naar 

> In het geval van de component Mark is dat het HTML-element `mark`.

en toen ging het wel mee ¯\_(ツ)_/¯

2024-11-13 06:17 UTC, rianrietveld approved these changes

2024-11-13 07:46 UTC, rianrietveld commented
En aanvullend: VoiceOver/Safari meldt het element `<mark>` niet.
Ik laat het maar zo, announcen moet dan maar uitgezocht worden bij de implementatie.

2024-11-13 08:03 UTC, rianrietveld commented
Na het schrijven van de component Mark wil ik gaag toch wat aanpassingen voorstellen:

Voeg bij de md files bovenin de licentie toe
`<!-- @license CC0-1.0 -->`

Ik heb bij de de codecomponent toegevoegd bij 1.3.1:

> Let op: Het element `<code>` wordt op het moment van schrijven (2024) nog niet ondersteund door hulpsoftware. Wellicht in de toekomst wel, dan is het goed om. nu alvast het juiste element te gebruiken.

2024-11-14 09:41 UTC, MarjonBakker commented
> @MarjonBakker beetje weird met de /, ik kon die niet comitten en ik zag um ook niet hierbij staan. Als workaround heb ik de tekst
> 
> > In het geval van het Mark component is dat het HTML-element `mark`.
> 
> Aangepast naar
> 
> > In het geval van de component Mark is dat het HTML-element `mark`.
> 
> en toen ging het wel mee ¯_(ツ)_/¯

Interessant. En aan 'de component' moet ik nog steeds wennen, kennelijk

2024-11-14 09:44 UTC, MarjonBakker commented
> Na het schrijven van de component Code wil ik graag toch wat aanpassingen voorstellen:
> 
> Voeg een changelog file toe.
> 
> Voeg bij de md files bovenin de licentie toe `<!-- @license CC0-1.0 -->`
> 
> Ik heb bij de de codecomponent toegevoegd bij 1.3.1:
> 
> > Let op: Het element `<code>` wordt op het moment van schrijven (2024) nog niet ondersteund door hulpsoftware. Wellicht in de toekomst wel, dan is het goed om nu alvast het juiste element te gebruiken.

@rianrietveld Volgens mij heb ik alles aangepast nu.

2024-11-14 10:02 UTC, rianrietveld requested changes

2024-11-14 10:02 UTC, rianrietveld commented on docs/componenten/mark/index.mdx
> +        "De achtergrondkleur van de Mark component heeft een contrast van minimaal 3:1 met de achtergrondkleur van de pagina",
Kun je dit conform maken met "Wanneer de achtergrondkleur van het Code Block anders is dan de default browserkleur, dan heeft deze een kleurcontrast van minimaal 3:1 met de achtergrondkleur van de pagina"

2024-11-14 10:05 UTC, rianrietveld approved these changes

2024-11-14 10:09 UTC, merged