fix: align multiline items w/ item text not marker
nl-design-system/documentatie pull request #1851
Opened 2024-12-23 16:14 UTC by hidde

2024-12-25 21:48 UTC, Robbert requested changes

2024-12-25 21:48 UTC, Robbert commented on src/components/AnatomyList.css
> +    var(--nl-anatomy-marker-min-inline-size, 2rem) + (4 * var(--nl-anatomy-marker-padding-inline, 0.125rem))
De `--nl-` prefix is bedoeld voor Hall of Fame componenten, niet voor de website.

2024-12-25 21:48 UTC, Robbert commented on src/components/AnatomyList.css
> +  inset-block-start: calc(-1 * var(--nl-anatomy-marker-padding-inline, 0.125rem));
Ik denk dat het niet klopt om `padding-inline` te koppelen aan de `block` axis. Als ik er bijvoorbeeld `1rem` van maak, dan ziet het er zo uit:

<img width="174" alt="Screenshot 2024-12-25 at 22 46 32" src="https://github.com/user-attachments/assets/3ea85a98-3fff-4f36-b19d-e878fcdcd841" />

2024-12-25 21:48 UTC, Robbert commented on src/components/AnatomyList.css
> +    var(--nl-anatomy-marker-min-inline-size, 2rem) + (4 * var(--nl-anatomy-marker-padding-inline, 0.125rem))
Waaruit volgt die `4 *`? Voelt als een magic number.

2024-12-27 10:17 UTC, hidde commented on src/components/AnatomyList.css
> +    var(--nl-anatomy-marker-min-inline-size, 2rem) + (4 * var(--nl-anatomy-marker-padding-inline, 0.125rem))
Kan ik eruit halen. Wil je dat ik ze er allemaal uithaal in deze file of was de rest wel de bedoeling?

2024-12-27 10:42 UTC, Robbert commented on src/components/AnatomyList.css
> +    var(--nl-anatomy-marker-min-inline-size, 2rem) + (4 * var(--nl-anatomy-marker-padding-inline, 0.125rem))
Voor anatomy-marker zou ik zet hernoemen, voor `nl-number-badge` kunnen ze blijven

2024-12-27 14:14 UTC, hidde commented on src/components/AnatomyList.css
> +    var(--nl-anatomy-marker-min-inline-size, 2rem) + (4 * var(--nl-anatomy-marker-padding-inline, 0.125rem))
heb 'm nu aangepast naar breedte + inline padding + tussenruimte. Dat was `1ch` en stond op de `::before`, maar is nu logischer op deze plek. Heb het een eigen custom property gegeven voor als iemand wil overriden.

2026-08-10 15:33 UTC, closed without merging