Voeg richtlijn “Meerdere stappen” toe
nl-design-system/documentatie pull request #543
Opened 2024-01-19 12:39 UTC by hidde

Deze hadden we bedacht als “Meerstappenformulier”. Als naam zou “Meerstappenformulieren” logischer zijn, omdat we ook “Links”, “Labels” etc in meervoud zeggen. Maar dan wordt het woord zo lang dat het niet op 1 regel past en afgebroken moet worden (althans, in onze lay-out). Vandaar mijn voorstel voor “Meerdere stappen”.

PR gebaseerd op [bijbehorende HackMD](https://hackmd.io/@rianrietveld/SkuTGtWOT?edit)

Draft, want to do: 

* [ ] Er zitten een aantal voorbeelden in die wel do's of don'ts zijn, maar niet echt lekker werken als visueel + codevoorbeeld, zoals een voorbeeld met `<title>`, dat als je het rendert niet wordt weergegeven, en het voorbeeld met stap boven of onder een kop. Hebben we een nieuw component nodig met Do/Don't header, maar zonder onderscheid tussen code en visuele weergave? (Kunnen we wsl op meer plekken gebruiken)

2024-01-26 12:42 UTC, rianrietveld commented
Opgelost met

```
  <Canvas
    language="html"
    code={<title>Stap 2 van 3, uw gegevens - Gemeente voorbeeld</title>}
    defaultCollapsed={false}
  ></Canvas>
```

2024-01-26 12:42 UTC, rianrietveld commented
@hidde kun je reviewen?

2024-01-26 17:34 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-step-count.md
> +- [1.3.2 Betekenisvolle volgorde](https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence.html) (niveau A).
SC 1.3.2 is ook relevant als we een beter voorbeeld willen geven dan GOV.UK voor de HTML. Wat mij betreft is "Stap 2 van 6" een ondertitel, en die tekst hoort daarom qua _document order_ ná de heading.

```html
<hgroup>
  <h1>Your details</h1>
  <p>Question 3 of 9</p>
</hgroup>
```

De visuele volgorde kan met flexbox via `order` aangepast worden. Bij utrecht is wordt dit aangeboden door de `heading-1`, `heading-group` en `pre-heading` componenten.

2024-01-26 17:34 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-step-count.md
> +- [3.2.3 Consistente navigation](https://www.w3.org/WAI/WCAG21/Understanding/consistent-navigation.html) (niveau AA)
"navigation" ➝ "navigatie"

2024-01-26 17:34 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-step-count.md
> +Aanpassen van de `<title>` in de `<head>` geldt voor WCAG ook voor dynamisch gegenereerde formulieren en dus ook voor de verschillende stappen.
"dynamisch gegenereerde formulieren" en "dynamische pagina's" is denk ik niet iets dat duidelijk is voor een multidisciplinaire doelgroep. Misschien zoiets?

---

Wanneer de gebruiker technisch gezien op dezelfde pagina blijft, en je met script de volgende formulierstap in beeld brengt, dan moet de paginatitel aangepast worden zodat die klopt bij de stap. Je kunt met script de titel aanpassen:

```js
document.title = "Stap 3 van 6: Adresgegevens";
```

---

Misschien moeten we als frontmatter keyword ook even `embedded form` toevoegen

2024-01-26 17:34 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-step-count.md
> +- Boven het formulier, bijvoorbeeld in het kopje van het formulier of vlak onder het kopje van het formulier.
Ook `aria-current="step"` suggereren voor 1.3.1?

2024-01-26 17:34 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-location.md
> +Zet inhoud die niet is gerelateerd aan formuliervelden altijd boven het formulier van elke stap. Dus zet informatie over de stappen **boven** en niet **binnen** het `<form>` element. Dan is de kans d
De verwoording  "inhoud die niet is gerelateerd aan formuliervelden" voelt alsof het gaat over inhoud die niet aan het formulier gerelateerd.

Misschien kunnen we het verwoorden als "Plaats tekst en uitleg die hoort bij het formulier buiten het `<form>` element. Dan is de kans dat screenreadergebruikers deze informatie missen het kleinst."

2024-01-26 17:34 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-location.md
> +- [Browse and focus modes](https://www.accessibility-developer-guide.com/knowledge/screen-readers/desktop/browse-focus-modes), Accessibility Developer Guide.
Zou deze informatie misschien beter tot zijn recht komen onder "Descriptions"? Dit geldt niet alleen voor multi-step forms.

2024-01-26 17:34 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-step-count-code.mdx
> +</Guideline>
Super dat dit voorbeeld er ook bij staat!

2024-01-26 17:34 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-consistency-code.mdx
> +        </p>
Dit voorbeeld zou extra duidelijk zijn als we een voorbeeld URL hebben: `<a href="./stap-1">Terug</a>` en `<a href="./stap-3">Volgende stap</a>`. Dan weet je zeker dat "Terug" niet over een ander concept gaat.

2024-01-26 17:34 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-consistency.md
> +- Volgende stap (of als laatste stap: Versturen) als submit button
Quotemarks voor link labels zouden de tekst duidelijker maken.

2024-01-26 17:34 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-consistency.md
> +Zorg er dus voor dat links en/of buttons binnen de formulieren op dezelfde plaats staan en dat ze ook een consistente naam hebben. Door consistentie heeft de gebruiker minder moeite de navigatie te b
"en/of" kan denk ik wel versimpeld worden tot "en", ik denk niet dat iemand zal denken: "oh nee, ik heb geen linkje of geen button in mijn formulier, dan moet ik dat fixen" 😅

2024-01-29 07:11 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-step-count.md
> +- [1.3.2 Betekenisvolle volgorde](https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence.html) (niveau A).
@Robbert 
Prima idee: `hgroup`, maar niet verplicht stellen, omdat dit niet zo makkelijk kan worden toegevegoed door een content manager met een formulierenplugin.

Wijzigen van de visuele volgorde ben ik geen fan van, maar kan het ook niet verbieden.

2024-01-29 07:15 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-step-count.md
> +Aanpassen van de `<title>` in de `<head>` geldt voor WCAG ook voor dynamisch gegenereerde formulieren en dus ook voor de verschillende stappen.
> frontmatter keyword ook even embedded form toevoegen

Wat wl je hier precies over vertellen?

2024-01-29 07:15 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-step-count.md
> +- Boven het formulier, bijvoorbeeld in het kopje van het formulier of vlak onder het kopje van het formulier.
@Robbert waar wil je aria-current="step" toevoegen in deze setup?

2024-01-29 07:45 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/multistep.mdx
> +- Geef duidelijk aan wanneer het formulier verzonden gaat worden.
@Robbert: is toegevoegd.

2024-01-29 07:45 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-timing.md
> +Maak duidelijk aan de gebruiker wanneer het formulier echt gaat worden verzonden. Goed gebruik (maar niet verplicht) is om de gebruiker als laatste stap een samenvatting te geven van wat is ingevuld
@Robbert: is toegevoegd.

2024-01-29 07:46 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-timing.md
> +De tekst van de laatste submit button kan dan bijvoorbeeld “Versturen” zijn, afhankelijk van de inhoud van het formulier.
@Robbert: is toegevoegd.

2024-01-29 07:46 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-step-count.md
> +- [3.2.3 Consistente navigation](https://www.w3.org/WAI/WCAG21/Understanding/consistent-navigation.html) (niveau AA)
@Robbert: is aangepast.

2024-01-29 07:47 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-step-count.md
> +Aanpassen van de `<title>` in de `<head>` geldt voor WCAG ook voor dynamisch gegenereerde formulieren en dus ook voor de verschillende stappen.
> frontmatter keyword ook even embedded form toevoegen

@robbert Wat wil je hier precies over vertellen?

De rest is aangepast.

2024-01-29 07:47 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-location.md
> +Zet inhoud die niet is gerelateerd aan formuliervelden altijd boven het formulier van elke stap. Dus zet informatie over de stappen **boven** en niet **binnen** het `<form>` element. Dan is de kans d
@Robbert: is aangepast.

2024-01-29 07:48 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-location.md
> +- [Browse and focus modes](https://www.accessibility-developer-guide.com/knowledge/screen-readers/desktop/browse-focus-modes), Accessibility Developer Guide.
@Robbert, @hidde graag even overleg

2024-01-29 07:48 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-consistency-code.mdx
> +        </p>
@Robbert: is aangepast.

2024-01-29 07:49 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-consistency.md
> +- Volgende stap (of als laatste stap: Versturen) als submit button
@Robbert: is aangepast.

2024-01-29 07:49 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-consistency.md
> +Zorg er dus voor dat links en/of buttons binnen de formulieren op dezelfde plaats staan en dat ze ook een consistente naam hebben. Door consistentie heeft de gebruiker minder moeite de navigatie te b
@Robbert: is aangepast.

2024-01-29 13:26 UTC, Robbert requested changes

2024-01-29 13:26 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-step-count.md
> +- Boven het formulier, bijvoorbeeld in het kopje van het formulier of vlak onder het kopje van het formulier.
Als er links zijn om naar andere stappen te gaan binnen het formulier, dan geef je waardevolle semantiek aan de link naar de huidige pagina.

Voorbeeld uit Open Formulieren:

<img width="1507" alt="Screenshot 2024-01-29 at 14 00 03" src="https://github.com/nl-design-system/documentatie/assets/30694/902cc3c2-6ac5-4dd8-bae1-5ed500ae31f5">

2024-01-29 13:26 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-location-code.mdx
> +</Guideline>
Ik vindt dit nog niet een heel sterk voorbeeld, omdat je niet super-essentiële informatie mist nu. Zullen we op de backlog iets toevoegen om hier een beter voorbeeld uit de praktijk toe te voegen? Ik stel me iets voor zoals:

- vraag 1: welke datum wil je trouwen?
- rich text met tabel met prijzen van trouwlocaties, met zeer uiteenlopende prijzen (essentiële info)
- vraag 2: welke locatie wil je trouwen?

2024-01-29 13:26 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_button-disabled.md
> +Disabled submitbuttons worden gebruikt om
Je zou het nu kunnen lezen als "Disabled submitbuttons worden gebruikt [in NL Design System]", hopelijk kunnen we dit misverstand voorkomen. Bijvoorbeeld:

"In de praktijk worden disabled submitbuttons vaak gebruikt"

2024-01-29 13:26 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_button-disabled.md
>  te verhinderen dat een gebruiker het formulier verzendt als nog niet alle waarden (goed) zijn ingevuld.
"(goed)" hoeft niet tussen haakjes, laten we de tekst zo simpel mogelijk houden.

2024-01-29 13:26 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_button-disabled.md
>  Er is een aantal toegankelijkheidsproblemen met het gebruik van disabled buttons:
De meest effectieve oplossing is inderdaad om disabled buttons niet te gebruiken, maar we kunnen een aantal praktische tips geven als de bestaande situatie niet gelijk aangepast kan worden:

- Gebruik voor de tekst disabled buttons voldoende contrast, zodat de tekst wel goed leesbaar is. Bijvoorbeeld: [#767676 met wit](https://nldesignsystem.nl/contrast/?background-color=%23757575&color=%23FFFFFF)
- Gebruik `tabindex="0"` zodat de button wel ontdekt kan worden door screenreadergebruikers.
- Leg uit wat je moet doen om zodat de button niet meer disabled is, koppel die tekst met `aria-describedby`.

2024-01-29 13:30 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-timing-code.mdx
> +        <button>Volgende</button>
Hoeft toch niet in een form als het the main submit knop is, omdat dat de default is?

2024-01-29 14:12 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-location.md
> +- [Browse and focus modes](https://www.accessibility-developer-guide.com/knowledge/screen-readers/desktop/browse-focus-modes), Accessibility Developer Guide.
Voorstel:
heb je uitgebreide info nodig bij een stuk: maak er een multisstep form van: om tekst goed te laten voorlezen (buiten het formulier).
Bij bij descriptions: vertellen waarom want form mode en JAWS. 

actie @rianrietveld

2024-01-31 07:38 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_button-disabled.md
>  Er is een aantal toegankelijkheidsproblemen met het gebruik van disabled buttons:
is toegevoegd

2024-01-31 07:39 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_button-disabled.md
>  te verhinderen dat een gebruiker het formulier verzendt als nog niet alle waarden (goed) zijn ingevuld.
is aangepast

2024-01-31 07:40 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_button-disabled.md
> +Disabled submitbuttons worden gebruikt om
is aangepast

2024-01-31 07:48 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-location-code.mdx
> +</Guideline>
Ik wil deze voorbeelden houden omdat het expliciet gaat over de locatie van de stappen.
We kunnen inderdaad bij de naloopronde kijken waar we info over niet gerelateerde info plaasten, zoals we al hebben besproken bij de descriptions etc.
Ik heb eenitem in het project richtlijnen aangemaakt
https://github.com/orgs/nl-design-system/projects/18?pane=issue&itemId=51722884

2024-01-31 09:28 UTC, rianrietveld commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-timing-code.mdx
> +<Guideline appearance="dont" title="Geef onduidelijk of een formulier verzonden gaat worden.">
is aangepast

2024-01-31 15:47 UTC, hidde commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-location-code.mdx
> +</Guideline>
Ok, backlog item is aangemaakt, ik markeer deze als “resolved”

2024-01-31 15:57 UTC, hidde commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-location.md
> +- [Browse and focus modes](https://www.accessibility-developer-guide.com/knowledge/screen-readers/desktop/browse-focus-modes), Accessibility Developer Guide.
Issue hiervoor gemaakt in https://github.com/nl-design-system/documentatie/issues/582 , dan kunnen we het als MVP zo laten als nu

2024-01-31 15:59 UTC, hidde commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-timing-code.mdx
> +        <button>Volgende</button>
type toegevoegd voor nu

2024-01-31 16:03 UTC, rianrietveld approved these changes
@hidde LGTM

2024-01-31 16:05 UTC, rianrietveld approved these changes
👍

2024-01-31 16:44 UTC, rianrietveld approved these changes
👍

2024-01-31 17:24 UTC, Robbert approved these changes

2024-01-31 17:24 UTC, merged