docs: uniform reference to WCAG SC
nl-design-system/documentatie pull request #587
Opened 2024-02-05 07:52 UTC by rianrietveld

Zie #542,
Verschillende soorten referentie naar aangepast naar: “X is nodig om te voldoen aan WCAG-criterium Y”.
En wat typos eruit gehaald.

2024-02-05 14:19 UTC, Robbert requested changes

2024-02-05 14:19 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_confirmation-accessibility.md
> +De succesmelding toegankelijk te maken voor alle gebruikers is nodig om te voldoen de WCAG-succescriteria:
"voldoen de" ➝ "voldoen aan de"

2024-02-05 14:19 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_link-in-new-tab.md
> +Hiermee volg de [WCAG-richtlijn 3.2 Voorspelbaar](https://www.w3.org/Translations/WCAG21-nl/#voorspelbaar): maak het uiterlijk en de bediening van webpagina's voorspelbaar.
"volg de" ➝ "volg je de"

2024-02-05 14:19 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-location.md
> +Het aangeven van de hoeveelheid stappen boven het formulier is nodig om te voldoen het WCAG-succescriterium [1.3.2 Betekenisvolle volgorde](https://www.w3.org/WAI/WCAG22/Understanding/meaningful-sequ
"voldoen het" ➝ "voldoen aan het"

2024-02-05 14:19 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_question-double.md
> +Gegevens niet meerdere keren binnen een formulier uit vragen is nodig om te voldoen het WCAG-Succescriterium [3.3.7 Overbodige Invoer](https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry.html
"voldoen het" ➝ "voldoen aan het"

2024-02-05 14:19 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_visual-design-field-size.md
> +Zorg dat het aanwijsgebied (aanklikbare deel) van radio buttons, checkboxes en icons tenminste 24 bij 24 pixels groot is. Dit is nodig om te voldoen WCAG-succescriterium [2.5.8 Grootte aanwijsgebied
"voldoen" ➝ "voldoen aan"

2024-02-05 14:19 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_visual-design-focus-visible.md
> +Voor gebruikers van een toetsenbord of van spraakherkenning moet duidelijk zijn welk formulierveld de focus heeft. Deze zogenaamde focusstijlen moeten consistent en duidelijk genoeg zijn. Goed zichtb
"voldoen het" ➝ "voldoen aan het"

2024-02-05 14:19 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_visual-design-focus-visible.md
> +Zorg ervoor dat de focusstijl een kleurcontrast heeft van tenminste 3:1 ten opzichte van de achtergrond van het formulierveld en de omringende achtergrond. Dit is nodig om te voldoen het WCAG-succesc
"voldoen het" ➝ "voldoen aan het"

2024-02-05 14:19 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_visual-design-order.md
> +Een logische volgorde van informatie is nodig om te voldoen het WCAG-succescriterium [1.3.2 Betekenisvolle volgorde](https://www.w3.org/WAI/WCAG22/Understanding/meaningful-sequence.html) (niveau A).
"voldoen het" ➝ "voldoen aan het"

2024-02-05 14:19 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_visual-design-text-contrast.md
> +Voldoende kleurcontrast van tekst is nodig om te voldoen het WCAG-succescriterium [1.4.3 Contrast (minimum)](https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html) (niveau AA).
"voldoen het" ➝ "voldoen aan het"

2024-02-05 14:19 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_visual-design-use-of-color.md
> +Gebruik van tekst naast kleur en icoontjes is nodig om te voldoen het WCAG-succescriterium [1.4.1 Gebruik van kleur](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html) (niveau A).
"voldoen het" ➝ "voldoen aan het"

2024-02-05 14:19 UTC, Robbert commented on docs/richtlijnen/formulieren/00-alle-richtlijnen/_when-which-compat.md
> +Ervoor zorgen dat iedereen een formulierelement kan bedienen en begrijpen is nodig om te voldoen de volgende WCAG-succescriteria:
"voldoen het" ➝ "voldoen aan het"

2024-02-06 05:43 UTC, rianrietveld commented
@Robbert bedankt voor het nalezen!
Ik heb nog een aantal extra gevonden, nu is het als het goed is correct.

2024-02-06 09:55 UTC, rianrietveld commented
@Robbert merge conflict is opgelost, wat mij betreft good
 to do

2024-02-06 10:58 UTC, Robbert approved these changes

2024-02-06 10:58 UTC, merged