wcag: 1.1.1
nl-design-system/documentatie pull request #591
Opened 2024-02-06 09:01 UTC by rianrietveld

Eerste SC 1.1.1 als ondersteuning voor de richtlijnen
related issue: #561

2024-02-06 09:04 UTC, rianrietveld commented
@Yolijn @Robbert 
Als test de eerste WCAG pagina.
Gaandeweg zal er meer content in komen.

What do you think ...

2024-02-06 17:52 UTC, Robbert requested changes
Je hebt mdx helemaal onder knie! 🏆

2024-02-06 17:52 UTC, Robbert commented on docs/richtlijnen/tekst-en-taalgebruik.md
> +Op 200Ok.nl staat een [alt-besluitboom](https://www.200ok.nl/tips/afbeeldingen/): wanneer en hoe kun je een alternatieve tekst toevoegen aan een afbeelding.
"alt-besluitboom" zouden we kunnen versimpelen tot "beslisboom".
"Besluitboom" staat trouwens niet op vandale.nl, "beslisboom" wel.
Zelfde bij Wikipedia: https://nl.wikipedia.org/wiki/Beslissingsboom

2024-02-06 17:52 UTC, Robbert commented on docs/wcag/1.1.1.mdx
> +- **Decoratie**, opmaak, onzichtbaar: Als niet-tekstuele content puur decoratief is, slechts voor visuele opmaak wordt gebruikt, of niet aan gebruikers wordt gerepresenteerd, dan wordt het op zo'n ma
Ik zou willen beginnen met de linkjes naar de W3C specificatie, en niet de tekst verbatim overnemen. Als mensen op zoek zijn naar de bron dan kunnen ze doorklikken naar de taal van hun keuze.

2024-02-06 17:52 UTC, Robbert commented on docs/wcag/1.1.1.mdx
> +- Nederlandse vertaling van het WCAG-succescriterium [1.1.1 Niet-tekstuele content](https://www.w3.org/Translations/WCAG21-nl/#tekstalternatieven).
Ik zou ook willen linken naar het Engelstalige origineel.

2024-02-06 17:52 UTC, Robbert commented on docs/wcag/1.1.1.mdx
> +- Engelstalige uitleg: [<span lang="en">Understanding SC 1.1.1:Non-text Content</span>](https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html).
uitleg ➝ toelichting?

2024-02-06 17:52 UTC, Robbert commented on docs/wcag/1.1.1.mdx
> +# WCAG Succescriterium 1.1.1 Niet-tekstuele content, niveau A
Wat denk je er van om niveau A niet zo prominent te vermelden? Misschien kunnen we het überhaupt achterwege laten, het zou kunnen helpen met de adoptie van bepaalde richtlijnen. ("AAA, die hoeft dus mooi niet")

Idee: we zouden eventueel onder het kopje "Testen" kunnen noemen, en dan alleen voor de AAA regels. Bij de contrast checker had ik het zo verwoord:

> Je mag de kleuren niet gebruiken voor tekst, als je wilt voldoen aan WCAG 2.2 AAA niveau.

We zouden dan iets kunnen zeggen als: "Je kunt de volgende tests kun je doen, als je wilt voldoen aan WCAG 2.2 AAA niveau."

2024-02-06 17:52 UTC, Robbert commented on docs/wcag/1.1.1.mdx
> +- De [alt-besluitboom](https://www.200ok.nl/tips/afbeeldingen/) van 200 OK: wanneer en hoe kun je een alternatieve tekst toevoegen aan een afbeelding.
alt-besluitboom ➝ beslisboom of "beslisboom voor alternatieve tekst bij afbeeldingen"?

2024-02-06 17:52 UTC, Robbert commented on docs/wcag/1.1.1.mdx
> +## Hoe te testen
AMAZING! Heel bruikbaar zo'n test-plan 🙌

2024-02-06 17:52 UTC, Robbert commented on docs/wcag/_cta_gebruikersonderzoek.md
> +Heb je gebruikersonderzoek gedaan dat betrekking heeft op dit succescriterium en wil je dit delen? Kijk eens bij [Gebruikersonderzoeken delen](https://gebruikersonderzoeken.nl/docs/onderzoek-delen/)
Ik ben geneigd om de schrijfwijzer van Amsterdam te volgen, die URLs altijd in lowercase doet:

https://www.amsterdam.nl/schrijfwijzer/heldere-taal-basis-onze-huisstijl/tekstonderdelen-heldere-taal/mailadressen-url'-links/

2024-02-06 17:52 UTC, Robbert commented on docs/wcag/1.1.1.mdx
> +- Audio: is er gesproken tekst in een audio dan moet deze beschikbaar zijn via uitgeschreven tekst (transcriptie).
"een audio" ➝ "de audio"

2024-02-06 17:54 UTC, Robbert commented
@Yolijn for your convenience: https://documentatie-git-guidelines-wcag-single-725392-nl-design-system.vercel.app/wcag/1.1.1

2024-02-06 18:03 UTC, Robbert reviewed
Wat is trouwens de reden dat we niet linken naar WCAG 2.2? Omdat de Nederlandse vertaling nog niet af is? Lijkt mIj wel logischer om —waar mogelijk— naar 2.2 te linken.

2024-02-07 05:34 UTC, rianrietveld commented on docs/richtlijnen/tekst-en-taalgebruik.md
> +Op 200Ok.nl staat een [alt-besluitboom](https://www.200ok.nl/tips/afbeeldingen/): wanneer en hoe kun je een alternatieve tekst toevoegen aan een afbeelding.
@Robbert dat is hoe Jules het genoemd heeft. Ik zal hem even pingen.
Compromis: Ik pas het aan naar alt-beslisboom. Wnat het is nogal een begrip in de a11y-wereld.

2024-02-07 05:43 UTC, rianrietveld commented on docs/wcag/1.1.1.mdx
> +- **Decoratie**, opmaak, onzichtbaar: Als niet-tekstuele content puur decoratief is, slechts voor visuele opmaak wordt gebruikt, of niet aan gebruikers wordt gerepresenteerd, dan wordt het op zo'n ma
Is aangepast.

2024-02-07 05:43 UTC, rianrietveld commented on docs/wcag/1.1.1.mdx
> +- Nederlandse vertaling van het WCAG-succescriterium [1.1.1 Niet-tekstuele content](https://www.w3.org/Translations/WCAG21-nl/#tekstalternatieven).
Is toegevoegd

2024-02-07 05:43 UTC, rianrietveld commented on docs/wcag/1.1.1.mdx
> +- Engelstalige uitleg: [<span lang="en">Understanding SC 1.1.1:Non-text Content</span>](https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html).
is aangepast

2024-02-07 05:44 UTC, rianrietveld commented on docs/wcag/1.1.1.mdx
> +# WCAG Succescriterium 1.1.1 Niet-tekstuele content, niveau A
Niveau is verwijderd

2024-02-07 05:45 UTC, rianrietveld commented on docs/wcag/1.1.1.mdx
> +- De [alt-besluitboom](https://www.200ok.nl/tips/afbeeldingen/) van 200 OK: wanneer en hoe kun je een alternatieve tekst toevoegen aan een afbeelding.
Is aangepast, zie (https://github.com/nl-design-system/documentatie/pull/591#discussion_r1480918391)

2024-02-07 05:46 UTC, rianrietveld commented on docs/wcag/_cta_gebruikersonderzoek.md
> +Heb je gebruikersonderzoek gedaan dat betrekking heeft op dit succescriterium en wil je dit delen? Kijk eens bij [Gebruikersonderzoeken delen](https://gebruikersonderzoeken.nl/docs/onderzoek-delen/)
is aangepast.

2024-02-07 05:46 UTC, rianrietveld commented on docs/wcag/1.1.1.mdx
> +- Audio: is er gesproken tekst in een audio dan moet deze beschikbaar zijn via uitgeschreven tekst (transcriptie).
is aangepast

2024-02-07 05:56 UTC, rianrietveld commented
> Wat is trouwens de reden dat we niet linken naar WCAG 2.2? Omdat de Nederlandse vertaling nog niet af is? Lijkt mIj wel logischer om —waar mogelijk— naar 2.2 te linken.

Als het goed is komt de NL vertaling er snel aan, alle discussies zijn gevoerd en het is nu nog wachten op het administratief proces.  Voor bestaande SC maakt het gelukkig qua tekst niet uit, omdat deze hetzelfde blijft.
Als de NL vertaling er is, zal ik de NL-links aanpassen naar 2.2.

De Engelstalige links gaan nu naar 2.2.

2024-02-07 06:25 UTC, rianrietveld commented
@Robbert / @Yolijn 
De opmerkingen van Robbert zijn verwerkt in
Online: https://documentatie-git-guidelines-wcag-single-725392-nl-design-system.vercel.app/wcag/1.1.1

2024-02-07 07:49 UTC, Robbert approved these changes

2024-02-07 07:52 UTC, merged

2024-02-21 08:13 UTC, rianrietveld commented
Issue: #624