wcag: adds 3.3.1 error identification.
nl-design-system/documentatie pull request #686
Opened 2024-02-23 07:13 UTC by rianrietveld

2024-02-23 07:44 UTC, Robbert requested changes

2024-02-23 07:44 UTC, Robbert commented on docs/wcag/3.3.1.mdx
> +- De automatische HTML-validatie van de browser is uitgeschakeld.
Kunnen we "HTML-validatie van de browser is uitgeschakeld" aanvullen met de directe doelen die we daarmee willen behalen? Dan is die browser-validatie niet een doel, maar een middel. We zouden de browser-validatie vermijden onder het lijstje kunnen noemen als de aanpak die we aanraden om diverse doelen te halen.

Bijvoorbeeld:
- de foutmelding staat niet over andere informatie heen
- de tekst van foutmelding heeft dezelfde vergroting (WCAG 1.4.4) en tekstafstand (WCAG 1.4.12) als de rest van de pagina

2024-02-23 07:44 UTC, Robbert commented on docs/wcag/3.3.1.mdx
> +- Er staat er boven het formulier een samenvatting van de foutmeldingen.
Misschien expliciet maken dat dit alleen ná verzenden is? Bijv.:

Wanneer de gebruiker een formulier verzend en er dan nog foutmeldingen zijn, staat er boven het formulier een samenvatting van alle foutmeldingen.

2024-02-23 07:44 UTC, Robbert commented on docs/wcag/3.3.1.mdx
> +Laat een gebruiker weten als er fouten zijn bij het invullen van een formulier. Vertel duidelijk en toegankelijk wanneer een formulierveld niet, of niet goed is ingevuld.
Duidelijk!

2024-02-26 08:38 UTC, rianrietveld commented on docs/wcag/3.3.1.mdx
> +- De automatische HTML-validatie van de browser is uitgeschakeld.
De belangrijkste reden van het uitschakelen van de browser-validatie is, dat het op dit moment niet toegankelijk is.  Bovendien geef je geeft de validatie uit handen. 

Je komt hier steeds op terug, ik zou graag samen met jou en Hidde over willen overleggen. Zodat we over browser-validatie en `required` een gezamenlijke duidelijke mening hebben, die ik in de documentatie eenduidig kan opschrijven bij de verschillende onderwerpen.

2024-02-26 08:42 UTC, rianrietveld commented on docs/wcag/3.3.1.mdx
> +- De automatische HTML-validatie van de browser is uitgeschakeld.
Ik heb er voor nu van gemaakt: De foutmeldingen worden niet automatisch door de browser gegenereerd. En de twee opties van jou toegevoegd.

2024-02-26 08:42 UTC, rianrietveld commented on docs/wcag/3.3.1.mdx
> +- Er staat er boven het formulier een samenvatting van de foutmeldingen.
Is aangepast

2024-02-27 12:55 UTC, Robbert approved these changes

2024-02-27 12:55 UTC, merged