Voeg FAQ toe als FAQ pagina
nl-design-system/documentatie pull request #771
Opened 2024-03-26 13:16 UTC by hidde

Context: https://github.com/nl-design-system/kernteam/issues/597 in de [Mediakit v1 milestone](https://github.com/nl-design-system/kernteam/milestone/66).

Hiermee voegen we de FAQ ook toe als FAQ. Antwoorden proberen zoveel mogelijk formuleringen te gebruiken als op elders op de site, maar worden soms door de vraag naar een net iets andere formulering gedwongen (feature, geen bug).

@Robbert de laatste vraag over security is nieuw en hebben we nog niet eerder gecheckt, wil je kritisch kijken naar of het antwoord klopt en goede voorbeelden geeft van wat we nu doen qua security?

2024-03-26 14:05 UTC, rianrietveld requested changes
@hidde duidelijk!
Heb wat tekstuele aanpassingen/verduidelijkingen

2024-03-26 14:05 UTC, rianrietveld commented on docs/project/faq.mdx
> +NL Design System wordt gebruikt in verschillende projecten van overheidsorganisaties door heel Nederland. Veel van deze projecten zijn in ontwikkeling, sommige projecten staan live. [Op onze website]
Linktekst zetten op 'overzicht van organisaties' en niet op 'Op onze website'.

2024-03-26 14:05 UTC, rianrietveld commented on docs/project/faq.mdx
> +- **Gebruik de bouwstenen**: gebruik [richtlijnen](/richtlijnen), [componenten](/componenten) of [onderzoek](/onderzoek) voor je websites en apps.
linken naar /richtlijnen/introductie

2024-03-26 14:05 UTC, rianrietveld commented on docs/project/faq.mdx
> +Het kernteam beheert de _repository's_ waarin de diverse NL Design System projecten publiek worden ontsloten, zoals thema's en organisatie-specifieke design systems.
_GitHub repositories_
link naar https://github.com/orgs/nl-design-system/repositories

2024-03-26 14:09 UTC, hidde commented on docs/project/faq.mdx
> +Het kernteam beheert de _repository's_ waarin de diverse NL Design System projecten publiek worden ontsloten, zoals thema's en organisatie-specifieke design systems.
```suggestion
Het kernteam beheert de [_repository's_](https://github.com/orgs/nl-design-system/repositories) waarin de diverse NL Design System projecten publiek worden ontsloten, zoals thema's en organisatie-specifieke design systems.
```

2024-03-26 14:09 UTC, hidde commented on docs/project/faq.mdx
> +- **Gebruik de bouwstenen**: gebruik [richtlijnen](/richtlijnen), [componenten](/componenten) of [onderzoek](/onderzoek) voor je websites en apps.
```suggestion
- **Gebruik de bouwstenen**: gebruik [richtlijnen](/richtlijnen/introductie), [componenten](/componenten) of [onderzoek](/onderzoek) voor je websites en apps.
```

2024-03-26 14:10 UTC, hidde commented on docs/project/faq.mdx
> +NL Design System wordt gebruikt in verschillende projecten van overheidsorganisaties door heel Nederland. Veel van deze projecten zijn in ontwikkeling, sommige projecten staan live. [Op onze website]
```suggestion
NL Design System wordt gebruikt in verschillende projecten van overheidsorganisaties door heel Nederland. Veel van deze projecten zijn in ontwikkeling, sommige projecten staan live. Op onze website vind je een [overzicht van organisaties](/community/wie-doet-mee/) die zelf en/of via hun leveranciers meedoen met NL Design System.
```

2024-03-26 14:12 UTC, hidde commented on docs/project/faq.mdx
> +In de community zijn al verschillende richtlijnen en componenten te vinden. Voor vragen, meld je gerust in de Slack-community van Code for NL.
```suggestion
In de community zijn al verschillende richtlijnen en componenten te vinden. Voor vragen, meld je gerust in de [Slack-community van Code for NL](https://praatmee.codefor.nl/) (kanaal `#nldesignsystem`).
```

2024-03-26 14:13 UTC, hidde commented on docs/project/faq.mdx
> +In de community zijn al verschillende richtlijnen en componenten te vinden. Voor vragen, meld je gerust in de Slack-community van Code for NL.
@Robbert wat zou je aanraden als plek om naar te lnken als men 'verschillende componenten' wil vinden? is Utrecht storybook dan logisch of juist onze eigen componentenpagina waar links staan?

2024-03-26 14:16 UTC, hidde commented on docs/project/faq.mdx
> +## Ik wil NL Design System gaan gebruiken voor mijn toegankelijkheidsopgave maar waar moet ik beginnen?
Goede vraag, voor nu een shortcut voor “voldoen aan de wettelijke verplichtingen en klantvriendelijkheidsambitie en daar een proces voor hebben ingericht” maar da's te lang.

2024-03-26 14:17 UTC, rianrietveld commented on docs/project/faq.mdx
> +Het kernteam beheert de _repository's_ waarin de diverse NL Design System projecten publiek worden ontsloten, zoals thema's en organisatie-specifieke design systems.
repository's is fout Engels :-) 
it's repositories

2024-03-26 14:20 UTC, hidde commented on docs/project/faq.mdx
> +Het kernteam beheert de _repository's_ waarin de diverse NL Design System projecten publiek worden ontsloten, zoals thema's en organisatie-specifieke design systems.
het is correct Nederlands blijkbaar, zoals [community's](https://www.digitaleoverheid.nl/communitys/). vind het zelf ook niet echt een gezicht moet ik zeggen.

2024-03-26 14:58 UTC, jeffreylauwers commented on docs/project/faq.mdx
> +Het kernteam van NL Design System krijgt soms vragen die regelmatig terugkomen. Op deze pagina geven we op een aantal antwoord, zodat ze makkelijk terug te vinden zijn.
```suggestion
Op deze pagina geven we antwoord op vragen die regelmatig aan het kernteam van NL Design System gesteld worden.
```

2024-03-26 14:59 UTC, jeffreylauwers commented on docs/project/faq.mdx
> +- [richtlijnen](/richtlijnen/introductie): adviezen over verschillende onderwerpen, zoals het [maken van formulieren](/richtlijnen/formulieren/).
```suggestion
- [Richtlijnen](/richtlijnen/introductie): adviezen over verschillende onderwerpen, zoals het [maken van formulieren](/richtlijnen/formulieren/).
```

2024-03-26 14:59 UTC, jeffreylauwers commented on docs/project/faq.mdx
> +- [componenten](/componenten): bouwblokken waarmee websites en applicaties kunnen worden opgebouwd, zoals knoppen, invulvelden en tabellen.
```suggestion
- [Componenten](/componenten): bouwblokken waarmee websites en applicaties kunnen worden opgebouwd, zoals knoppen, invulvelden en tabellen.
```

2024-03-26 14:59 UTC, jeffreylauwers commented on docs/project/faq.mdx
> +- [patronen](/voorbeelden/patronen): voorbeelden van hoe componenten samen kunnen worden gebruikt voor specifieke taken die gebruikers willen doen, op basis van inzichten uit [gebruikersonderzoek](/v
```suggestion
- [Patronen](/voorbeelden/patronen): voorbeelden van hoe componenten samen kunnen worden gebruikt voor specifieke taken die gebruikers willen doen, op basis van inzichten uit [gebruikersonderzoek](/voorbeelden/onderzoek).
```

2024-03-26 15:02 UTC, jeffreylauwers commented on docs/project/faq.mdx
> +- [handboek](/handboek/introductie): documentatie over het gebruik van NL Design System.
Deze de verwijzing naar Handboek zou ik, bovenaan zetten, weglaten of een andere plek geven. De reden hiervoor is de zin die hier direct achteraan komt. Het handboek ontstaat niet in de community.

```suggestion
- [Handboek](/handboek/introductie): documentatie over het gebruik van NL Design System.
```

2024-03-26 15:04 UTC, jeffreylauwers commented on docs/project/faq.mdx
> +Deze onderdelen ontstaan niet bij het kernteam, maar in de community. Bijvoorbeeld omdat een gemeente of ministerie een specifiek component nodig heeft.
We spreken hier expliciet over 'component'. Maar hierboven benoemen we Richtlijnen, Componenten en Patronen. Zouden we dan het volgende moeten doen om het zo algemener te maken als enkel componenten?

```suggestion
Deze onderdelen ontstaan niet bij het kernteam, maar in de community. Bijvoorbeeld omdat een gemeente of ministerie een specifiek component of patroon nodig heeft.
```

2024-03-26 15:04 UTC, jeffreylauwers commented on docs/project/faq.mdx
> +Als blijkt dat meer organisaties datzelfde component willen gebruiken, wordt er samengewerkt aan een ultieme versie, waarop het kernteam regie voert, kwaliteit bewaakt en garanties geeft. Dit doen we
Zie comment hierboven. Ook hier spreken we enkel over 'component'.

2024-03-26 15:06 UTC, jeffreylauwers commented on docs/project/faq.mdx
> +De aanpak binnen NL Design System om samen te werken noemen we het “[estafettemodel](/handboek/estafettemodel)”. Hierin krijgen richtlijnen, componenten en patronen een status, die aangeeft hoe ver z
```suggestion
De aanpak binnen NL Design System om samen te werken noemen we het '[estafettemodel](/handboek/estafettemodel)'. Hierin krijgen richtlijnen, componenten en patronen een status, die aangeeft hoe ver ze zijn gevorderd. Zo gaan onderdelen van '[Help Wanted](/handboek/estafettemodel#help-wanted)' naar '[Community](/handboek/estafettemodel#community)' naar '[Candidate](/handboek/estafettemodel#candidate)' naar '[Hall of Fame](/handboek/estafettemodel#hall-of-fame)'. Elke stap heeft een eigen checklist, waarmee we kwaliteit waarborgen en bepalen wie wat doet.
```

2024-03-26 15:06 UTC, jeffreylauwers commented on docs/project/faq.mdx
> +Elke stap heeft ook een eigen doel. De “Community” stap geeft organisaties alle vrijheid om te innoveren en van elkaar te gebruiken. In de “Candidate” stap is het onderdeel algemener gemaakt, breder
```suggestion
Elke stap heeft ook een eigen doel. De 'Community' stap geeft organisaties alle vrijheid om te innoveren en van elkaar te gebruiken. In de 'Candidate' stap is het onderdeel algemener gemaakt, breder ingezet en klaar voor de laatste feedback. Tot slot wordt het onderdeel definitief in de 'Hall of Fame' stap, met garanties op toegankelijkheid en gebruiksvriendelijkheid.
```

2024-03-26 15:08 UTC, jeffreylauwers commented on docs/project/faq.mdx
> +NL Design System wordt gebruikt in verschillende projecten van overheidsorganisaties door heel Nederland. Veel van deze projecten zijn in ontwikkeling, sommige projecten staan live. Op onze website v
Als je dit leest ben je al op 'onze website'

2024-03-26 15:19 UTC, jeffreylauwers commented on docs/project/faq.mdx
> +- **Gebruik de bouwstenen**: gebruik [richtlijnen](/richtlijnen/introductie), [componenten](/componenten) of [onderzoek](/onderzoek) voor je websites en apps.
Eerder schrijven we 'websites en applicaties' hier dan ook?

```suggestion
- **Gebruik de bouwstenen**: gebruik [richtlijnen](/richtlijnen/introductie), [componenten](/componenten) of [onderzoek](/onderzoek) voor je websites en applicaties.
```

2024-03-26 15:20 UTC, jeffreylauwers commented on docs/project/faq.mdx
> +Het kernteam beheert de [_repository's_](https://github.com/orgs/nl-design-system/repositories) waarin de diverse NL Design System projecten publiek worden ontsloten, zoals thema's en organisatie-spe
Dit stond italic?

```suggestion
Het kernteam beheert de [repository's](https://github.com/orgs/nl-design-system/repositories) waarin de diverse NL Design System projecten publiek worden ontsloten, zoals thema's en organisatie-specifieke design systems.
```

2024-03-26 15:21 UTC, jeffreylauwers commented on docs/project/faq.mdx
> +We passen best practices toe om te zorgen dat deze repository's up to date en veilig blijven, zoals automatisch instellen van rechten, _branch protection_ en procedures voor het regelmatig updaten va
Dit stond italic?

```suggestion
We passen best practices toe om te zorgen dat deze repository's up to date en veilig blijven, zoals automatisch instellen van rechten, branch protection en procedures voor het regelmatig updaten van dependency's.
```

2024-03-26 15:24 UTC, jeffreylauwers commented on docs/project/faq.mdx
> +## Waarom maken jullie niet gewoon zelf componenten, richtlijnen en ontwerpen en stellen die beschikbaar?
Eerder spreken we over richtlijnen, componenten en patronen. Dus dat ritme hier ook aanhouden? En dan minus 'Richtlijnen' omdat we die inmiddels toch echt wel zelf maken?

```suggestion
## Waarom maken jullie niet gewoon zelf componenten en patronen?
```

2024-03-26 15:25 UTC, jeffreylauwers commented on docs/project/faq.mdx
> +We ontwerpen de onderdelen niet zelf, omdat we de doelen van deelnemende organisaties centraal willen stellen. En, nog belangrijker, de behoeften van hun gebruikers. Doordat specialisten in de commun
Met 'ontwikkelen' design en development te pakken?

```suggestion
We ontwikkelen de onderdelen niet zelf, omdat we de doelen van deelnemende organisaties centraal willen stellen. En, nog belangrijker, de behoeften van hun gebruikers. Doordat specialisten in de community samenwerken stimuleren we vanaf het begin breed draagvlak. Zo worden oplossingen direct in de praktijk gebruikt en kunnen ze gelijk met de juiste doelgroep worden getest.
```

2024-03-26 15:27 UTC, jeffreylauwers commented on docs/project/faq.mdx
> +We ontwerpen de onderdelen niet zelf, omdat we de doelen van deelnemende organisaties centraal willen stellen. En, nog belangrijker, de behoeften van hun gebruikers. Doordat specialisten in de commun
We spreken hier trouwens over 'onderdelen'. Zou dat niet een mooi woord zijn om richtlijnen, componenten en patronen, continue mee samen te vatten in 1 woord?

2024-03-26 19:05 UTC, hidde commented on docs/project/faq.mdx
> +- [handboek](/handboek/introductie): documentatie over het gebruik van NL Design System.
```suggestion

Er is ook een [handboek](/handboek/introductie), documentatie over het gebruik van NL Design System.
```

2024-03-26 19:06 UTC, hidde commented on docs/project/faq.mdx
> +Als blijkt dat meer organisaties datzelfde component willen gebruiken, wordt er samengewerkt aan een ultieme versie, waarop het kernteam regie voert, kwaliteit bewaakt en garanties geeft. Dit doen we
```suggestion
Als blijkt dat meer organisaties datzelfde component of patroon willen gebruiken, wordt er samengewerkt aan een ultieme versie, waarop het kernteam regie voert, kwaliteit bewaakt en garanties geeft. Dit doen we met het [estafettemodel](/handboek/estafettemodel)”. Hierin krijgen richtlijnen, componenten en patronen een status, die aangeeft hoe ver ze zijn gevorderd.
```

2024-03-26 19:07 UTC, hidde commented on docs/project/faq.mdx
> +Als blijkt dat meer organisaties datzelfde component willen gebruiken, wordt er samengewerkt aan een ultieme versie, waarop het kernteam regie voert, kwaliteit bewaakt en garanties geeft. Dit doen we
ik maak er nog ff typographer's quotes van:

```suggestion
Als blijkt dat meer organisaties datzelfde component willen gebruiken, wordt er samengewerkt aan een ultieme versie, waarop het kernteam regie voert, kwaliteit bewaakt en garanties geeft. Dit doen we met het ‘[estafettemodel](/handboek/estafettemodel)’. Hierin krijgen richtlijnen, componenten en patronen een status, die aangeeft hoe ver ze zijn gevorderd.
```

2024-03-26 19:08 UTC, hidde commented on docs/project/faq.mdx
> +De aanpak binnen NL Design System om samen te werken noemen we het “[estafettemodel](/handboek/estafettemodel)”. Hierin krijgen richtlijnen, componenten en patronen een status, die aangeeft hoe ver z
```suggestion
De aanpak binnen NL Design System om samen te werken noemen we het ‘[estafettemodel](/handboek/estafettemodel)’. Hierin krijgen richtlijnen, componenten en patronen een status, die aangeeft hoe ver ze zijn gevorderd. Zo gaan onderdelen van ‘[Help Wanted](/handboek/estafettemodel#help-wanted)’ naar ‘[Community](/handboek/estafettemodel#community)’ naar ‘[Candidate](/handboek/estafettemodel#candidate)’ naar ‘[Hall of Fame](/handboek/estafettemodel#hall-of-fame)’. Elke stap heeft een eigen checklist, waarmee we kwaliteit waarborgen en bepalen wie wat doet.
```

2024-03-26 19:08 UTC, hidde commented on docs/project/faq.mdx
> +Elke stap heeft ook een eigen doel. De “Community” stap geeft organisaties alle vrijheid om te innoveren en van elkaar te gebruiken. In de “Candidate” stap is het onderdeel algemener gemaakt, breder
```suggestion
Elke stap heeft ook een eigen doel. De ‘Community’ stap geeft organisaties alle vrijheid om te innoveren en van elkaar te gebruiken. In de ‘Candidate’ stap is het onderdeel algemener gemaakt, breder ingezet en klaar voor de laatste feedback. Tot slot wordt het onderdeel definitief in de ‘Hall of Fame’ stap, met garanties op toegankelijkheid en gebruiksvriendelijkheid.
```

2024-03-26 19:09 UTC, hidde commented on docs/project/faq.mdx
> +We ontwerpen de onderdelen niet zelf, omdat we de doelen van deelnemende organisaties centraal willen stellen. En, nog belangrijker, de behoeften van hun gebruikers. Doordat specialisten in de commun
Ja, in veel gevallen wel! Zou het willen laten afhangen van of we ergens tactisch concreet willen zijn (en dus langer) of dat we liever kort zijn.

2024-03-26 19:17 UTC, hidde commented on docs/project/faq.mdx
> +NL Design System wordt gebruikt in verschillende projecten van overheidsorganisaties door heel Nederland. Veel van deze projecten zijn in ontwikkeling, sommige projecten staan live. Op onze website v
```suggestion
NL Design System wordt gebruikt in verschillende projecten van overheidsorganisaties door heel Nederland. Veel van deze projecten zijn in ontwikkeling, sommige projecten staan live. Op de pagina [‘Wie doet mee?’](/community/wie-doet-mee/) vind je een overzicht van organisaties die zelf en/of via hun leveranciers meedoen met NL Design System.
```

2024-03-26 19:20 UTC, hidde commented on docs/project/faq.mdx
> +Het kernteam beheert de _repository's_ waarin de diverse NL Design System projecten publiek worden ontsloten, zoals thema's en organisatie-specifieke design systems.
Ja je hebt helemaal gelijk, dat suggereert dat het Engels is… nu niet meer schuin!

2024-03-28 12:06 UTC, hidde commented on docs/project/faq.mdx
> +In de community zijn al verschillende richtlijnen en componenten te vinden. Voor vragen, meld je gerust in de [Slack-community van Code for NL](https://praatmee.codefor.nl/) (kanaal `#nldesignsystem`
```suggestion
In de community zijn al veel verschillende [richtlijnen](/richtlijnen) en [componenten](/componenten) te vinden. De richtlijnen zijn direct op deze website te vinden, voor de componenten kun je terecht bij de organisaties waar ze gemaakt zijn. Op de pagina [componenten](/componenten) vind je links naar de relevante Storybooks en Figma-bestanden.

Voor vragen, design of development: meld je gerust in de [Slack-community van Code for NL](https://praatmee.codefor.nl/) (kanaal `#nldesignsystem`).
```

2024-03-28 12:09 UTC, Robbert commented on docs/project/faq.mdx
> +Het kernteam beheert de [repository's](https://github.com/orgs/nl-design-system/repositories) waarin de diverse NL Design System projecten publiek worden ontsloten, zoals thema's en organisatie-speci
```suggestion
Het kernteam helpt de community om hun [repository's](https://github.com/orgs/nl-design-system/repositories) vers en veilig te houden, zodat iedereen gerust gebruik kan maken van de componenten en thema's.

- Alle code wordt verplicht door een tweede teamlid gecontroleerd.
- Elke dag worden backups gemaakt van de NL Design System projecten op GitHub.
- Elke maand werken we samen om updates te installeren.
- De updates gaan niet automatisch, alle wijzigingen worden door twee personen gecontroleerd.
- Organisaties die werken op [github.com/nl-design-system](github.com/nl-design-system) worden [geholpen met infrastructuur](http://github.com/nl-design-system/terraform) die toegang tot de code en de integriteit van de code bewaakt.
- Twee-factor-authenticatie (2FA) is verplicht voor alle bijdragen aan NL Design System.
- Alle code controleren we automatisch op secure coding practices, en voldoen aan die regels is verplicht.
```

2024-03-28 12:11 UTC, hidde commented on docs/project/faq.mdx
> +- [Welke NLDS-richtlijnen en componenten kan ik nu direct gebruiken om mijn website digitaal, gebruiksvriendelijk en toegankelijk te krijgen?](#welke-nlds-richtlijnen-en-componenten-kan-ik-nu-direct-
```suggestion
- [Welke richtlijnen en componenten kan ik nu direct gebruiken om mijn website digitaal, gebruiksvriendelijk en toegankelijk te krijgen?](#welke-nlds-richtlijnen-en-componenten-kan-ik-nu-direct-gebruiken-om-mijn-website-digitaal-gebruiksvriendelijk-en-toegankelijk-te-krijgen)
```

2024-03-28 13:08 UTC, Robbert commented on docs/project/faq.mdx
> +Overheidsorganisaties hebben veel overlap in de online diensten die ze aanbieden. Die overlap maakt samenwerken logisch en dat doen wij als community. Want als we dezelfde uitdagingen hebben, kunnen
De community begon in 2017 toen werd opgemerkt dat er veel overlap is in de online diensten die overheidsorganisaties aanbieden, dat veel ontwikkelwerk en gebruikersonderzoek dubbel wordt gedaan, en toch slechts een fractie van de overheidssites toegankelijk en gebruiksvriendelijk is. Zou veel meer samenwerken en de oplossingen verzamelen niet een goede oplossing zijn?

De groeiende community is nog altijd het hart van dit project. Sinds 2020 heeft het Ministerie van Binnenlandse Zaken budget beschikbaar gesteld voor een kernteam dat de community ondersteunt, zodat meer organisaties makkelijker kunnen meewerken.

2024-03-28 13:08 UTC, Robbert commented on docs/project/faq.mdx
> +Voor vragen, design of development: meld je gerust in de [Slack-community van Code for NL](https://praatmee.codefor.nl/) (kanaal `#nldesignsystem`).
Binnenkort kunnen we zoiets toevoegen:

Heb je een oplossing nodig voor een probleem van een specifiek WCAG succescriterium uit je toegankelijkheidsverklaring? Kijk dan op XXXX.

2024-03-28 13:15 UTC, Robbert commented on docs/project/faq.mdx
> +1. Onze richtlijnen worden gebruikt als kennisbank. Ze bevatten concrete adviezen over wat er nodig is en waarom. Er zijn do's en don'ts, uitleg van de [WCAG-criteria](https://www.w3.org/Translations
Zou het niet tactisch zijn om het woord "kennisbank" te vermijden, ivm digitoegankelijk.nl?

2024-03-28 13:15 UTC, Robbert commented on docs/project/faq.mdx
> +1. Onze richtlijnen worden gebruikt als kennisbank. Ze bevatten concrete adviezen over wat er nodig is en waarom. Er zijn do's en don'ts, uitleg van de [WCAG-criteria](https://www.w3.org/Translations
In plaats van "uitleg van de WCAG-criteria" (dat is niet echt ons doel), denk ik dat we beter kunnen adverteren met "voorbeelden waarmee je kunt voldoen aan WCAG-criteria" of iets dergelijks.

2024-03-28 13:15 UTC, Robbert commented on docs/project/faq.mdx
> +2. Onze componenten kunnen worden gebruikt om toegankelijke producten te maken. Als componenten de laatste fase hebben bereikt (Hall of Fame), garanderen we zelfs dat ze voldoen aan toegankelijkheids
Op de vraag "Waar moet ik beginnen" is het denk ik niet helpful om de niet bestaande hall of fame componenten te noemen, at this stage.

2024-03-28 13:15 UTC, Robbert commented on docs/project/faq.mdx
> +Meedoen is gratis en kan stap voor stap. De kosten voor organisaties zitten in het beschikbaar stellen van resources en de tijd vrijmaken waarin ze samenwerken.
Beestje bij z'n naam noemen? "Tijd en geld"?

2024-03-28 13:41 UTC, Robbert commented on docs/project/faq.mdx
> +Overheidsorganisaties hebben veel overlap in de online diensten die ze aanbieden. Die overlap maakt samenwerken logisch en dat doen wij als community. Want als we dezelfde uitdagingen hebben, kunnen
I guess wat ik hier bedoel is dat het project niet de community heeft gemaakt, maar andersom :)

2024-03-28 13:45 UTC, hidde commented on docs/project/faq.mdx
> +- [Patronen](/voorbeelden/patronen): voorbeelden van hoe componenten samen kunnen worden gebruikt voor specifieke taken die gebruikers willen doen, op basis van inzichten uit [gebruikersonderzoek](/v
ik twijfel (:D) of we het weg moeten halen… wel belangrijk detail dat het alleen mogelijke richtingen en niet per se _de_ richting.

2024-03-28 13:45 UTC, hidde commented on docs/project/faq.mdx
> +Er is ook een [handboek](/handboek/introductie), documentatie over het gebruik van NL Design System.
nice!

2024-03-28 13:49 UTC, hidde commented on docs/project/faq.mdx
> +Meedoen is gratis en kan stap voor stap. De kosten voor organisaties zitten in het beschikbaar stellen van resources en de tijd vrijmaken waarin ze samenwerken.
zit in “kosten”? “tijd en geld vrijmaken waarin ze samenwerken” werkt niet?

2024-03-28 13:53 UTC, hidde commented on docs/project/faq.mdx
> +- [Componenten](/componenten): bouwblokken waarmee websites en applicaties kunnen worden opgebouwd, zoals knoppen, invulvelden en tabellen.
```suggestion
- [Componenten](/componenten): bouwblokken waarmee websites en applicaties worden opgebouwd, zoals knoppen, invulvelden en tabellen.
```

2024-03-28 13:56 UTC, hidde commented on docs/project/faq.mdx
> +1. Onze richtlijnen worden gebruikt als kennisbank. Ze bevatten concrete adviezen over wat er nodig is en waarom. Er zijn do's en don'ts, uitleg van de [WCAG-criteria](https://www.w3.org/Translations
```suggestion
1. Onze richtlijnen worden gebruikt als kennisbank. Ze bevatten concrete adviezen over wat er nodig is en waarom. Er zijn do's en don'ts, voorbeelden waarmee je aan[WCAG](https://www.w3.org/Translations/WCAG21-nl/) kunt voldoen en tips die verder dan gaan de WCAG.
```

2024-03-28 14:06 UTC, hidde commented on docs/project/faq.mdx
> +Het doel: organisaties hoeven minder vaak hetzelfde wiel uit te vinden. Zo worden online overheidsomgevingen consistenter, gebruiksvriendelijker en toegankelijker.
```suggestion
Het doel: organisaties hoeven minder vaak hetzelfde wiel uit te vinden, en hebben meer tijd om gebruikers centraal te stellen. Zo worden online overheidsomgevingen consistenter, gebruiksvriendelijker en toegankelijker.
```

2024-03-28 14:06 UTC, hidde commented on docs/project/faq.mdx
> +- [Hoe werkt het NL Design System en waarom?](#hoe-werkt-het-nl-design-system-en-waarom)
```suggestion
- [Hoe werkt het NL Design System](#hoe-werkt-het-nl-design-system)
```

2024-03-28 14:07 UTC, hidde commented on docs/project/faq.mdx
> +## Hoe werkt het NL Design System en waarom?
```suggestion
## Hoe werkt het NL Design System?
```

2024-03-28 14:11 UTC, hidde commented on docs/project/faq.mdx
> +Overheidsorganisaties hebben veel overlap in de online diensten die ze aanbieden. Die overlap maakt samenwerken logisch en dat doen wij als community. Want als we dezelfde uitdagingen hebben, kunnen
het is goede context, maar lijkt mij teveel detail voor deze pagina, werkt denk ik beter in een presentatie?

2024-03-28 14:13 UTC, hidde commented on docs/project/faq.mdx
> +2. Onze componenten kunnen worden gebruikt om toegankelijke producten te maken. Als componenten de laatste fase hebben bereikt (Hall of Fame), garanderen we zelfs dat ze voldoen aan toegankelijkheids
Hm… leek me nuttig om de garantie waarover men misschien heeft gehoord te koppelen aan hall of fame…

2024-03-28 14:15 UTC, Robbert submitted a review, later dismissed

2024-03-28 14:21 UTC, hidde commented on docs/project/faq.mdx
> +Meedoen is gratis en kan stap voor stap. De kosten voor organisaties zitten in het beschikbaar stellen van resources en de tijd vrijmaken waarin ze samenwerken.
```suggestion
Meedoen is gratis en kan stap voor stap. De kosten voor organisaties zitten in het beschikbaar stellen van mensen en de tijd vrijmaken waarin ze samenwerken.
```

2024-03-28 14:31 UTC, Robbert approved these changes
🚀 Ship it!

2024-03-28 14:31 UTC, merged

2024-03-28 15:22 UTC, RenateNLDS commented on docs/project/faq.mdx
> +NL Design System is een project dat specialisten van verschillende overheidsorganisaties laat samenwerken aan concrete oplossingen voor websites en applicaties. Denk bijvoorbeeld aan code, ontwerp en
Hoewel ik deze suggestie goed vind, vind ik de zin te lang. Kunnen we hier losse zinnen van maken @hidde ? Bijvoorbeeld: 
NL Design System is een project dat meer samenwerking mogelijk maakt van specialisten die werken aan concrete oplossingen voor websites en applicaties, bij verschillende overheidsorganisaties. Ze delen en ontwikkelen herbruikbare code, ontwerpen en richtlijnen.

2024-03-28 15:26 UTC, RenateNLDS commented on docs/project/faq.mdx
> +Overheidsorganisaties hebben veel overlap in de online diensten die ze aanbieden. Die overlap maakt samenwerken logisch en dat doen wij als community. Want als we dezelfde uitdagingen hebben, kunnen
Toch vind ik die eerste zin die @Robbert noemt wel een goede (en sterke) toevoeging. Het geeft een soort van vertrouwen dat het niet 'net nieuw' is ofzo. Misschien kunnen we dit toevoegen als: De community is ontstaan in 2017 toen bleek dat er veel overlap was in de vele online diensten die overheidsorganisaties aanbieden. Die overlap maakt samenwerken logisch en dat doen wij als community..... etc.

2024-03-28 15:27 UTC, RenateNLDS commented on docs/project/faq.mdx
> +Meedoen is gratis en kan stap voor stap. De kosten voor organisaties zitten in het beschikbaar stellen van resources en de tijd vrijmaken waarin ze samenwerken.
Beter om resources te vervangen door mensen!