style: automatically set correct user-select for guidelines
nl-design-system/documentatie pull request #945
Opened 2024-05-22 13:23 UTC by bddjong

2024-05-22 21:38 UTC, Yolijn requested changes

2024-05-22 21:38 UTC, Yolijn commented on src/components/Canvas/Canvas.tsx
> +  copy = true,
Dit zorgt er nu voor dat je juist voor de foute voorbeelden een copy knop krijgt.

<img width="773" alt="Screenshot 2024-05-22 at 23 03 29" src="https://github.com/nl-design-system/documentatie/assets/877246/7ba814a5-10f0-4f75-a755-a4f148ed2b97">

Er zijn denk ik een paar oplossingen, weet niet welke minst vies is. Hier op volgorde van viesheid in mijn hoofd de opties die ik denk dat er zijn:
1. Maak `copy=false` weer default en voeg aan elke `Canvas` die `appearance="do"` is een `copy` attribuut toe.
2. Maak een extra className voor de toolbar rondom de `copy` button en geef deze design tokens waarmee je de toolbar vanuit `Guideline` can hiden.
3. Voeg een React context toe om in Canvas op te vragen of de state van Guideline do of don't is
4. Geef canvas als een argument mee aan `Guideline` zodat je copy er zelf op kan zetten.

2024-05-23 08:56 UTC, bddjong commented on src/components/Canvas/Canvas.tsx
> +  copy = true,
Offline besproken om voor optie 2 te gaan zodat dit alsnog automatisch kan gebeuren

2024-05-26 20:21 UTC, Yolijn approved these changes

2024-05-26 20:21 UTC, merged